calc/urls.py
from django.conf.urls import url

from . import views

app_name = 'calc'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<test>[0-9]+)/result/$', views.result, name='result'),
    
    # ex: /polls/5/
    #url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    # ex: /polls/5/vote/
    # url(r'^(?P<question_id>[0-9]+)/result/$', views.vote, name='result'),
]

newCalc/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from calc import views as v
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#from django.conf.urls import include

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    #css
    url(r'^$', v.index),
    url(r'^calc/', include('calc.urls')),


    #css
    #url(r'^$', v.index),
]
urlpatterns += staticfiles_urlpatterns()

calc/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

calc/views.py
#from django.shortcuts import render

from django.http import HttpResponse

from django.http import HttpResponse
from .models import Question
from django.shortcuts import render, render_to_response
from math import pi

def index(request):
    #return render(request, 'index.html')
    #return render(request, 'calc/index.html')
    return render_to_response('calc/index.html')


# def result(request, can_height):
#     return render(request, 'calc/result.html', {'canHeight': can_height})

# def result(request):
#     if request.method == "POST":
#         list_values = request.POST.getlist('my_list')
#     return render(request, 'calc/result.html', {'list': list_values})

def result(request, test):
    if request.method == "GET":
        can_height= request.GET['canHeight']
        can_radius = request.GET['canRadius']
    tuple = calculate(float(can_radius), float(can_height))
    return render(request, 'calc/result.html', {
        'canHeight': can_height,
        'canRadius': can_radius,
        'tuple': tuple,
        'wastedSpace': tuple[1],
        'numOfCans': tuple[0]
    })


def calculate(Cd, Ch ):
    # Cd = 0.02
    # Ch = 0.10
    # volume of can/box
    Vb = (Cd * Cd * Ch)
    Vs = 32.2514

    # maximun number of cans that will fit in the shipping container
    maxCans = int(Vs / Vb)
    print("maximun number of cans that will fit in the shipping container: ", maxCans)

    wasteSp = (32.2514 - (maxCans * Ch * pi * (Cd / 2) ** 2))
    # volume of wasted space
    print("volume of wasted space: ", wasteSp, "m^3")

    return (maxCans, wasteSp)
    # General concensus: long skinny cans create less wasted space.

calc/templates/calc/index.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Calculus Canning Calculator</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static 'vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="{% static 'css/creative.min.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Tobin and June :)</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#about">Calculate</a>
                    </li>

                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1 id="homeHeading">Calculus Canning Calculator</h1>
                <hr>

                <a href="#about" class="btn btn-primary btn-xl page-scroll">Calculate!</a>
            </div>
        </div>
    </header>








    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h1 class="section-heading">calculate by entering the height and width</h1>
                    <hr class="light">
                    

            <div style="font-family: Verdana; font-weight: normal; font-size: 20px; color: gray;">
            <form action="{% url 'calc:result' 100 %}" method="get">
            {% csrf_token %}
                <label style="font-weight: normal;">Interior Volume of the Shipping Container: 32.2514 m^3</label><br>
                <label style="font-weight: normal;"> Can Height: </label>

                <input type="text" name="canHeight" id="02" value="" /><br>
                <label style="font-weight: normal;">Can Radius: </label>

                <input type="text" name="canRadius" id="03" value="" /><br>
                
                <hr class="light">
                <input type="submit" value="Crunch The Numbers" />
            </form>
            </div>
                    
                    
                </div>
            </div>
        </div>
    </section>













    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Contact Us!</h2>
                    <hr class="primary">
                </div>


                <div class="col-lg-4 col-lg-offset-2 text-center">
                    <i class="fa fa-github fa-3x" aria-hidden="true"></i>
                    <p>tobinP</p>

                </div>


                <div class="col-lg-4 text-center">
                    <i class="fa fa-github fa-3x" aria-hidden="true"></i>
                    <p>junecaden</p>
                </div>
            </div>
        </div>
    </section>

    <!-- jQuery -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="{% static 'vendor/scrollreveal/scrollreveal.min.js' %}"></script>
    <script src="{% static 'vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'js/creative.min.js' %}"></script>

</body>

</html>

calc/templates/calc/result.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Calculus Canning Calculator</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static 'vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="{% static 'css/creative.min.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Tobin and June :)</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#about">Calculate</a>
                    </li>

                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1 id="homeHeading">RESULTS</h1>
                <hr>

                	<p>
					<label style="color: white;">Can Height: {{ canHeight }}</label> <br>
					<label style="color: white;">Can Radius: {{ canRadius }}</label> <br><br>

					<label style="color: white;">Number of cans: {{ numOfCans}} </label><br>
					<label style="color: white;">Wasted Space: {{ wastedSpace}} </label><br>
                	</p>

            </div>
        </div>
    </header>



</body>

</html>